# Common Labels
labels:
  app: "casemanagement"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "casemanagement"


# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "casemanagement_service_schema"
    image:
      repository: "docker.io/venkatramireddyb/pucar_casemanagement_db"
      tag: develop-12a6777df80150083198f97ee14e57a0cacecd3f
# Container Configs
image:
  repository: "docker.io/venkatramireddyb/pucar_casemanagement"
  tag: develop-12a6777df80150083198f97ee14e57a0cacecd3f
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
debugPort: 8000
remote_debug:
  enabled: true
appType: "java-spring"
heap: "-Xmx64m -Xms64m -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
java-args: "-Dspring.profiles.active=monitoring"
memory_limits: 640Mi
healthChecks:
  enabled: true
  livenessProbePath: "/casemanagement/health"
  readinessProbePath: "/casemanagement/health"



env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: "SCHEMA_TABLE"
    value: "casemanagement_service_schema"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_LOCALIZATION_SEARCH_ENDPOINT
    value: /localization/messages/v1/_search
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /casemanagement
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        key: individual
        name: egov-service-host
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_URL_SHORTNER
    valueFrom:
      configMapKeyRef:
        key: egov-url-shortening
        name: egov-service-host
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_ADVOCATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: advocate
  - name: EGOV_INDEXER_ES_HOST_NAME
    valueFrom:
      configMapKeyRef:
        key: es-host
        name: egov-config
  - name: EGOV_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        key: es-indexer-host
        name: egov-config
  - name: EGOV_INDEXER_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: username
  - name: EGOV_INDEXER_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: password
  - name: EGOV_PDF_HOST
    valueFrom:
      configMapKeyRef:
        key: pdf-service
        name: egov-service-host
  - name: DRISTI_DEV_TASK_SEARCH_HOST
    valueFrom:
      configMapKeyRef:
        key: task
        name: egov-service-host
  - name: DRISTI_DEV_ORDER_SEARCH_HOST
    valueFrom:
      configMapKeyRef:
        key: order
        name: egov-service-host
  - name: DRISTI_DEV_FILE_SEARCH_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-filestore
        name: egov-service-host
  - name: SPRING_DATA_REDIS_HOST
    value: "redis.backbone"
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  - name: EGOV_CREDENTIAL_HOST
    valueFrom:
      configMapKeyRef:
        key: sunbirdrc-credential-service
        name: egov-service-host
  - name: DRISTI_CASE_HOST
    valueFrom:
      configMapKeyRef:
        key: case
        name: egov-service-host
  - name: EGOV_DRISTI_PDF_HOST
    valueFrom:
      configMapKeyRef:
        key: dristi-pdf
        name: egov-service-host
  - name: CASEMANAGEMENT_KAFKA_WORKFLOW_TRANSITION_TOPIC
    value: save-wf-transitions
  - name: EGOV_DRISTI_PDF_PROCESS_BUNDLE
    value: egov-pdf/dristi-pdf/process-case-bundle
  - name: GENERATE_VC_CODE
    value: "Pucar.SummonOrder14"
  - name: SPRING_DATASOURCE_WRITER_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_DATASOURCE_READER_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_DATASOURCE_WRITER_USERNAME
    valueFrom:
      secretKeyRef:
        key: writeusername
        name: db
  - name: SPRING_DATASOURCE_READER_USERNAME
    valueFrom:
      secretKeyRef:
        key: readusername
        name: db
  - name: SPRING_DATASOURCE_WRITER_PASSWORD
    valueFrom:
      secretKeyRef:
        key: writepassword
        name: db
  - name: SPRING_DATASOURCE_READER_PASSWORD
    valueFrom:
      secretKeyRef:
        key: readpassword
        name: db

  
