# Common Labels
labels:
  app: "egov-filestore"
  group: "core"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_filestore_schema"
    image:
      repository: "docker.io/venkatramireddyb/egov-filestore-db"
      tag: main-98ec8dc97569afa6e1e52c0b43a95d596c9dd1d3

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "filestore"

# Container Configs
image:
  repository: "docker.io/venkatramireddyb/egov-filestore"
  tag: main-98ec8dc97569afa6e1e52c0b43a95d596c9dd1d3
replicas: "2"
healthChecks:
  enabled: true
  livenessProbePath: "/filestore/health"
  readinessProbePath: "/filestore/health"
appType: "java-spring"
tracing-enabled: true
is-bucket-fixed: "true"
#fixed-bucketname: "unified-dev-bucket-s3"
heap: "-Xmx1g -Xms1g"
file-storage-mount-path: "/filestore"
is-nfs-enabled: false
is-azure-storage-enabled: false
is-container-fixed: "true"
is-s3-enabled: "true"

persistence:
  enabled: false

# Additional Container Envs
env: |
  - name: LOGGING_LEVEL_ROOT
    value: "ERROR"
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_DEBUG_PORT
    value: "5005"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  - name: FILE_STORAGE_MOUNT_PATH
    value: {{ index .Values "file-storage-mount-path" | quote }}
  - name: TEMP_FOLDER_PATH
    value: "/tmp"
  - name: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
    value: "200MB"
  - name: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
    value: 1000MB
  - name: MAX_FILE_SIZE
    value: "500000000"
  - name: ISNFSSTORAGEENABLED
    value: {{ index .Values "is-nfs-enabled" | quote }}
  {{- if index .Values "is-nfs-enabled" }}
  - name: DISK_STORAGE_HOST_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: SOURCE_DISK
    value: "diskStorage"
  {{- end }}
  {{- if index .Values "is-s3-enabled" }}
  - name: ISS3ENABLED
    value: "true"
  {{else}}
  - name: ISS3ENABLED
    value: "false"
  {{- end }}  
  {{- if index .Values "minio-enabled" }}
  - name: AWS_KEY
    valueFrom:
      secretKeyRef:
        key: minioaccesskey
        name: egov-filestore
  - name: AWS_SECRETKEY
    valueFrom:
      secretKeyRef:
        key: miniosecretkey
        name: egov-filestore
  {{- else if index .Values "is-azure-storage-enabled"}}
  - name: AZURE_ACCOUNTNAME
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: azureaccountname
  - name: AZURE_ACCOUNTKEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: azuresecretkey
  - name: ISAZURESTORAGEENABLED
    value: "true"
  {{else}}
  - name: AWS_KEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: awskey
  - name: AWS_SECRETKEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: awssecretkey
  {{- end }}
  {{- if index .Values "is-bucket-fixed" }}
  - name: IS_BUCKET_FIXED
    value: {{ index .Values "is-bucket-fixed" | quote }}
  {{- end }}
  {{- if index .Values "is-container-fixed" }}
  - name: IS_CONTAINER_FIXED
    value: {{ index .Values "is-container-fixed" | quote }}
  {{- end }}
  {{- if index .Values "fixed-bucketname" }}
  - name: FIXED_BUCKETNAME
    value: {{ index .Values "fixed-bucketname" | quote }}
  {{- end }}
  {{- if index .Values "fixed-container-name" }}
  - name: FIXED_CONTAINER_NAME
    value: {{ index .Values "fixed-container-name" | quote }}
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: ALLOWED_FORMATS_MAP
    value: {{ index .Values "allowed-file-formats-map" | quote }}
  {{- if index .Values "minio-enabled" }}  
  - name: MINIO_URL
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: minio-url
  {{- end }}
  {{- if index .Values "filestore-url-validity" }}   
  - name: PRESIGNED_URL_EXPIRY_TIME_IN_SECS     
    value: {{ index .Values "filestore-url-validity" | quote }}   
  {{- end }}