# Common Labels
labels:
  app: "digit-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "docker.io/venkatramireddyb/digit-ui"
  tag: v1.0.0-d6576c3d536fa779c0ec2e0341d788821550841f
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/ui/"
  readinessProbePath: "/ui/"

extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-ui

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
