# Common Labels
labels:
  app: "icops-integration"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
#  zuul: true
  context: "kerala-icops"
#healthChecks:
#  enabled: true
#  livenessProbePath: "/kerala-icops/health"
#  readinessProbePath: "/kerala-icops/health"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "integration_service_schema"
    image:
      repository: "docker.io/venkatramireddyb/integration_db"
      tag: v1.0.0-2ee8513e9dcefdb51c4eb7d38be4d6661c665167
# Container Configs
image:
   repository: "docker.io/venkatramireddyb/integration"
   tag: v1.0.0-2ee8513e9dcefdb51c4eb7d38be4d6661c665167
replicas: "1"

env: |
  - name: TOMCAT_MAX_HTTP_POST_SIZE
    value: "104857600"
  - name: JAVA_OPTS
    value: -Xmx128m -Xms128m
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_FILE_STORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_SUMMONS_HOST
    valueFrom:
      configMapKeyRef:
        key: summons
        name: egov-service-host
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: SERVICE_NAME
    valueFrom:
      configMapKeyRef:
        key: service-name
        name: egov-config
  - name: SERVICE_KY
    valueFrom:
      configMapKeyRef:
        key: service-ky
        name: egov-config
  - name: AUTH_TYPE
    valueFrom:
      configMapKeyRef:
        key: auth-type
        name: egov-config
  - name: EGOV_OAUTH_URL
    valueFrom:
      configMapKeyRef:
        key: egov-oauth-url
        name: egov-service-host



