# Common Labels
labels:
  app: "oncourts-website"
  group: "web"

# Ingress Configs
ingress:
  enabled: false
  context: "home"


httpPort: 3000
# Container Configs
image:
  repository: "docker.io/venkatramireddyb/oncourts-landing-page"
  tag: develop-be1164682b9b84e7a77b6a54fae1096e5d3f5160

env: |
  - name: ONCOURTS_API_ENDPOINT
    value: https://dristi-kerala-uat.pucar.org
  
  - name: ONCOURTS_CITIZEN_APP_ENDPOINT
    value: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/login
  
  - name: ONCOURTS_EMPLOYEE_APP_ENDPOINT
    value: https://dristi-kerala-uat.pucar.org/digit-ui/employee/login



