{{- with index .Values "secrets" "db" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
stringData:
  username: {{ .username | quote }}
  password: {{ .password | quote }}
  flyway-username: {{ .flywayUsername | quote }}
  flyway-password: {{ .flywayPassword | quote }}
  writeusername: {{ .writeusername | quote }}
  writepassword: {{ .writepassword | quote }}
  readusername: {{ .readusername | quote }}
  readpassword: {{ .readpassword | quote }}
{{- end }}
