{{- with index .Values "secrets" "db" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  username: {{ .username | quote | b64enc | quote }}
  password: {{ .password | quote | b64enc | quote }}
  flyway-username: {{ .flywayUsername | quote | b64enc | quote }}
  flyway-password: {{ .flywayPassword | quote | b64enc | quote }}
{{- end }}
