{{- with index .Values "secrets" "egov-pg-service" }}
{{- if gt (len .) 2  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  axismerchantid: {{  .axis_merchant_id | quote | b64enc | quote }}
  axismerchantsecret: {{  .axis_merchant_secretkey | quote | b64enc | quote }}
  axismerchantuser: {{  .axis_merchant_user | quote | b64enc | quote }}
  axismerchantpwd: {{  .axis_merchant_pwd | quote | b64enc | quote }}
  axismerchantaccesscode: {{  .axis_merchant_accesscode | quote | b64enc | quote }}
  payumerchantkey: {{  .payu_merchant_key | quote | b64enc | quote }}
  payumerchantsalt: {{  .payu_merchant_salt | quote | b64enc | quote }}
{{- end }}
{{- end }}