# Common Labels
labels:
  app: "hearing-management"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "hearing-management"


healthChecks:
  enabled: true
  livenessProbePath: "/hearing-management/health"
  readinessProbePath: "/hearing-management/health"

# Container Configs
image:
  repository: "docker.io/venkatramireddyb/hearing-management"
  tag: develop-6416f71f46c8815c5d4cb36bed8273d9a1c17e1a
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
java-args: "-Dspring.profiles.active=monitoring"
heap: "-Xmx256m -Xms256m -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
debugPort: 8000
remote_debug:
  enabled: true
memory_limits: 640Mi
env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /hearing-management
  - name: DRISTI_HEARING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hearing
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user