# Common Labels
labels:
  app: "hearing-scheduled-completed-cron"
  group: "cronjobs"

# Cron schedule
cron:
  schedule: "0 18 * * *"
  timezone: "Asia/Kolkata"

# Container Configs
namespace: cronjobs
image:
  repository: "docker.io/venkatramireddyb/cronjob"
  tag: "v1"

command: 
  - "bin/sh" 
  - "-c"
  - |
    curl -X POST --location "http://hearing.egov:8080/hearing/v1/_runCronJob"