# Common Labels
labels:
  app: "task-management"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "task-management"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "task_management_schema"
    image:
      repository: "docker.io/venkatramireddyb/task-management-db"
      tag: feature-payment-redesign-local-changes-b8af2df2ea35b860552f388065fe8c5e04afc75e

# Init Containers Configs
healthChecks:
  enabled: true
  livenessProbePath: "/task-management/health"
  readinessProbePath: "/task-management/health"

# Container Configs
image:
  repository: "docker.io/venkatramireddyb/task-management"
  tag: feature-payment-redesign-local-changes-b8af2df2ea35b860552f388065fe8c5e04afc75e
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
java-args: "-Dspring.profiles.active=monitoring"
heap: "-Xmx256m -Xms192m"
debugPort: 5005
memory_limits: 384Mi
env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /task-management
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: DRISTI_ORDER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: order
  - name: DRISTI_TASK_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: task
  - name: DRISTI_CASE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_BILLING_SERVICE_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: PAYMENT_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: payment-calculator
  - name: EGOV_ETREASURY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: etreasury
