# Common Labels
labels:
  app: "inportal-survey"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "inportal-survey"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "inportal_survey_schema"
    image:
      repository: "docker.io/venkatramireddyb/inportal-survey-db"
      tag: feature-3939-inportal-survey-service-7a9bff733dc31bcd7edf241673ebcac6749d571f

# Init Containers Configs
healthChecks:
  enabled: true
  livenessProbePath: "/inportal-survey/health"
  readinessProbePath: "/inportal-survey/health"

# Container Configs
image:
  repository: "docker.io/venkatramireddyb/inportal-survey"
  tag: feature-3939-inportal-survey-service-7a9bff733dc31bcd7edf241673ebcac6749d571f
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
java-args: "-Dspring.profiles.active=monitoring"
heap: "-Xmx256m -Xms256m"
debugPort: 8000
remote_debug:
  enabled: true
memory_limits: 512Mi
env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /inportal-survey
