# Common Labels
labels:
  app: "summons"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "summons"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "summons_schema"
    image:
      repository: "docker.io/venkatramireddyb/summons-svc_db"
      tag: feature-4334-order84-85-0c4f91fe30c11a769fc5994f0285a4999db16c1b


# Container Configs
image:
  repository: "docker.io/venkatramireddyb/summons-svc"
  tag: feature-4334-order84-85-0c4f91fe30c11a769fc5994f0285a4999db16c1b
replicas: "1"
healthChecks:
   enabled: true
   livenessProbePath: "/summons-svc/health"
   readinessProbePath: "/summons-svc/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx64m -Xms64m"
java-args: "-Dspring.profiles.active=monitoring"
debugPort: 5005

# Additional Container Envs
env: |          
  - name: DRISTI_COURT_NAME
    valueFrom:
      configMapKeyRef:
        key: COURT_NAME
        name: egov-config
  - name: DRISTI_COURT_ADDRESS
    valueFrom:
      configMapKeyRef:
        key: COURT_ADDRESS
        name: egov-config
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_FILE_STORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_PDF_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: EGOv_ICOPS_HOST
    valueFrom:
      configMapKeyRef:
        key: icops-integration
        name: egov-service-host      
  - name: PAYMENT_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        key: payment-calculator
        name: egov-service-host       
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: billing-service
        name: egov-service-host 
  - name: EGOV_TASK_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: task
        name: egov-service-host
  - name: DRISTI_DEV_ORDER_SEARCH_HOST
    valueFrom:
      configMapKeyRef:
        key: order
        name: egov-service-host
  - name: EGOV_EPOST_HOST
    valueFrom:
      configMapKeyRef:
        key: epost
        name: egov-service-host
  - name: EGOV_CASE_HOST
    valueFrom:
      configMapKeyRef:
        key: case
        name: egov-service-host
  - name: TREASURY_DEMAND_HOST
    valueFrom:
      configMapKeyRef:
        key: etreasury
        name: egov-service-host
  - name: DRISTI_EVIDENCE_HOST
    valueFrom:
      configMapKeyRef:
        key: evidence
        name: egov-service-host