# Common Labels
labels:
  app: "e-sign-svc"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "e-sign-svc"


# Init Containers Configs
e-sign-svc:
  initContainers:
    dbMigration:
      enabled: true
      schemaTable: "e_sign_svc_schema"
      image:
        repository: "docker.io/venkatramireddyb/pucar_e-sign-svc-db"
        tag: develop-e64b5dc7d9b818e381b4f0a858692fc44edc11be
# Container Configs
image:
  repository: "docker.io/venkatramireddyb/pucar_e-sign-svc"
  tag: develop-e64b5dc7d9b818e381b4f0a858692fc44edc11be
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
memory_limit: 512Mi
debugPort: 5005

env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: SERVER_PORT
    value: "8080"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: ESING_RESPONSE_URL
    valueFrom:
      configMapKeyRef:
        key: esign-interceptor
        name: egov-config
  - name: ESIGN_ASP_ID
    valueFrom:
      configMapKeyRef:
        key: esign-id
        name: egov-config
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"

    
