# Common Labels
labels:
  app: "epayments"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "epayments"


# Container Configs
image:
  repository: "docker.io/venkatramireddyb/epayments"
  tag: bug-4258-fc452ab98954dfc0f18a3b94ed23e657fbc992a2
replicas: "1"

env: |
  - name: EXTERNAL_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-services
        name: egov-config
  - name: SERVER_URL
    valueFrom:
      configMapKeyRef:
        key: etreasury
        name: egov-config
  - name: DRISTI_URL
    valueFrom:
      configMapKeyRef:
        key: dristi-url
        name: egov-config