# Common Labels
labels:
  app: "openapi"
  group: "backend"

# Ingress Configs
ingress:
  enabled: true
  context: "openapi"



healthChecks:
  enabled: true
  livenessProbePath: "/health"
  readinessProbePath: "/health"
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "openapi_service_schema"
    image:
      repository: "docker.io/venkatramireddyb/openapi-db"
      tag: develop-1a74c7135d21b08a63af0c98d3cba2c4643d3670
# Container Configs
image:
  repository: "docker.io/venkatramireddyb/pucar_openapi"
  tag: develop-64544fb50f20302915a9a766883b0106b1e9a8cf
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
java-args: "-Dspring.profiles.active=monitoring"
heap: "-Xmx256m -Xms256m"
debugPort: 5005
memory_limits: 640Mi
env: |
  - name: MANAGEMENT_HEALTH_REDIS_ENABLED
    value: "false"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /OpenAPI
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_LOCALIZATION_SEARCH_ENDPOINT
    value: /_search
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        key: individual
        name: egov-service-host
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: HEARING_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: hearing
        name: egov-service-host
  - name: CASE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-mdms-service
        name: egov-service-host
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-idgen
        name: egov-service-host
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-user
        name: egov-service-host
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-hrms
        name: egov-service-host
  - name: EGOV_URL_SHORTNER
    valueFrom:
      configMapKeyRef:
        key: egov-url-shortening
        name: egov-service-host
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: EGOV_INBOX_HOST
    valueFrom:
      configMapKeyRef:
        key: inbox
        name: egov-service-host
  - name: EGOV_ADVOCATE_HOST
    valueFrom:
      configMapKeyRef:
        key: advocate
        name: egov-service-host
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-filestore
        name: egov-service-host
  - name: BAIL_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: bail-bond
        name: egov-service-host
  - name: ESIGN_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: e-sign-svc
        name: egov-service-host
  - name: EVIDENCE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: evidence
  - name: esign.service.endpoint
    value: "e-sign-svc/v1/_esign"
  - name: EGOV_BILLING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_ETREASURY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: etreasury
  - name: EGOV_TASK_MANAGEMENT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: task-management
  - name: EGOV_PAYMENT_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: payment-calculator
  - name: EGOV_LOCK_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: lock-service
  - name: EGOV_ORDER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: order
  - name: EGOV_CASE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: EGOV_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        key: es-indexer-host
        name: egov-config
  - name: EGOV_INDEXER_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: username
  - name: EGOV_INDEXER_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: password
  - name: DRISTI_ANALYTICS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: analytics
